# Generated by Django 3.2.12 on 2024-05-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignment_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('report', models.CharField(max_length=120)),
                ('reg_no', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='login_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=120)),
                ('attendence', models.CharField(max_length=120)),
                ('system_no', models.CharField(max_length=120)),
                ('user_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Logout_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('system_no', models.CharField(max_length=120)),
                ('user_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('reg_no', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('system_no', models.CharField(max_length=50)),
                ('status', models.CharField(default='present', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_library.register')),
            ],
        ),
    ]
